cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "_cell_guid": "b1076dfc-b9ad-4769-8c92-a6c4dae69d19",
    "_uuid": "8f2839f25d086af736a60e9eeb907d3b93b6e0e5",
    "editable": false,
    "trusted": true
   },
   "outputs": [],
   "source": [
    "# This Python 3 environment comes with many helpful analytics libraries installed\n",
    "# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n",
    "# For example, here's several helpful packages to load\n",
    "\n",
    "import numpy as np # linear algebra\n",
    "import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n",
    "import openai as openai\n",
    "\n",
    "# Input data files are available in the read-only \"../input/\" directory\n",
    "# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n",
    "\n",
    "import os\n",
    "for dirname, _, filenames in os.walk('/kaggle/input'):\n",
    "    for filename in filenames:\n",
    "        print(os.path.join(dirname, filename))\n",
    "\n",
    "# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n",
    "# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "editable": false
   },
   "source": [
    "*Imports and Setup*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "editable": false,
    "trusted": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 25.2 -> 25.3\n",
      "[notice] To update, run: C:\\Users\\susha\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "# Cell A: Imports & Setup\n",
    "%pip install openai --quiet\n",
    "\n",
    "import os\n",
    "import json\n",
    "from datetime import datetime, timedelta\n",
    "import pandas as pd\n",
    "import openai\n",
    "\n",
    "# Put your API key into Kaggle notebook Secrets or set here (not recommended in plain text)\n",
    "# openai.api_key = os.getenv(\"OPENAI_API_KEY\")\n",
    "openai.api_key = \"AIzaSyClKQChIXg_qkOmpgHgxCQKwMJB5a19GMQ\"  # replace or use Kaggle secrets\n",
    "\n",
    "MODEL = \"gpt-4o\"  # or \"gpt-4\" or \"gpt-4o-mini\" depending on availability"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell B: Utility functions\n",
    "def parse_tasks(task_list):\n",
    "    \"\"\"\n",
    "    task_list: list of dicts: {\"title\": str, \"deadline\": \"YYYY-MM-DD\", \"estimate_hours\": float, \"priority\": optional int}\n",
    "    Return normalized list with deadline datetime.\n",
    "    \"\"\"\n",
    "    normalized = []\n",
    "    for t in task_list:\n",
    "        d = t.get(\"deadline\")\n",
    "        try:\n",
    "            dd = datetime.fromisoformat(d) if d else None\n",
    "        except:\n",
    "            dd = None\n",
    "        normalized.append({\n",
    "            \"title\": t[\"title\"],\n",
    "            \"deadline\": dd,\n",
    "            \"estimate_hours\": float(t.get(\"estimate_hours\", 1)),\n",
    "            \"priority\": int(t.get(\"priority\", 2))  # 1-high,2-medium,3-low\n",
    "        })\n",
    "    return normalized\n",
    "\n",
    "def score_task(task, today=None):\n",
    "    \"\"\"\n",
    "    Simple heuristic score: lower score => do earlier\n",
    "    score = days_left / priority_weight / estimate_hours\n",
    "    \"\"\"\n",
    "    if today is None:\n",
    "        today = datetime.now()\n",
    "    if task[\"deadline\"] is None:\n",
    "        days_left = 999\n",
    "    else:\n",
    "        days_left = max(1, (task[\"deadline\"] - today).days)\n",
    "    priority_weight = {1: 0.6, 2: 1.0, 3: 1.5}[task[\"priority\"]]\n",
    "    return days_left * priority_weight * task[\"estimate_hours\"]\n",
    "\n",
    "def prioritize(tasks):\n",
    "    tasks_with_score = []\n",
    "    for t in tasks:\n",
    "        t2 = t.copy()\n",
    "        t2[\"score\"] = score_task(t)\n",
    "        tasks_with_score.append(t2)\n",
    "    tasks_sorted = sorted(tasks_with_score, key=lambda x: x[\"score\"])\n",
    "    return tasks_sorted\n",
    "\n",
    "def split_task_into_subtasks(title, hours):\n",
    "    \"\"\"\n",
    "    Heuristic split: convert estimate hours into chunks (50-90 min study sessions)\n",
    "    \"\"\"\n",
    "    chunk = 1.5  # hours per study chunk\n",
    "    num = max(1, int((hours + 0.49) // chunk))\n",
    "    subtasks = [f\"{title} — Study session {i+1}/{num} (~{round(hours/num,2)} hrs)\" for i in range(num)]\n",
    "    return subtasks\n",
    "\n",
    "def generate_daily_plan(prioritized_tasks, daily_hours_available):\n",
    "    \"\"\"\n",
    "    Distribute tasks into days, greedily fill daily_hours_available\n",
    "    Returns dict mapping date->list of (title, hours)\n",
    "    \"\"\"\n",
    "    plan = {}\n",
    "    today = datetime.now().date()\n",
    "    day = 0\n",
    "    remaining = []\n",
    "    for t in prioritized_tasks:\n",
    "        remaining.append({\"title\": t[\"title\"], \"hours\": t[\"estimate_hours\"], \"deadline\": t[\"deadline\"]})\n",
    "\n",
    "    while remaining and day < 30:  # stop after 30 days fallback\n",
    "        date = today + timedelta(days=day)\n",
    "        cap = daily_hours_available\n",
    "        plan.setdefault(date.isoformat(), [])\n",
    "        i = 0\n",
    "        while i < len(remaining) and cap > 0:\n",
    "            item = remaining[i]\n",
    "            if item[\"hours\"] <= cap:\n",
    "                plan[date.isoformat()].append({\"title\": item[\"title\"], \"hours\": item[\"hours\"]})\n",
    "                cap -= item[\"hours\"]\n",
    "                remaining.pop(i)\n",
    "            else:\n",
    "                plan[date.isoformat()].append({\"title\": item[\"title\"], \"hours\": cap})\n",
    "                item[\"hours\"] -= cap\n",
    "                cap = 0\n",
    "                i += 1\n",
    "        day += 1\n",
    "    return plan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell C: LLM wrapper and prompt templates\n",
    "\n",
    "def call_llm(system_prompt, user_prompt, model=MODEL, max_tokens=600):\n",
    "    resp = openai.ChatCompletion.create(\n",
    "        model=model,\n",
    "        messages=[\n",
    "            {\"role\":\"system\",\"content\":system_prompt},\n",
    "            {\"role\":\"user\",\"content\":user_prompt}\n",
    "        ],\n",
    "        max_tokens=max_tokens,\n",
    "        temperature=0.2\n",
    "    )\n",
    "    return resp[\"choices\"][0][\"message\"][\"content\"].strip()\n",
    "\n",
    "SYSTEM_PROMPT = \"\"\"You are a helpful student productivity assistant. Produce concise, structured JSON\n",
    "when asked to output schedules, subtasks, or study routines. Keep tone encouraging but direct.\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell D: Orchestrator\n",
    "def run_student_agent(student_profile):\n",
    "    \"\"\"\n",
    "    student_profile: {\n",
    "        \"name\": str,\n",
    "        \"daily_hours\": float,\n",
    "        \"tasks\": [ {\"title\",\"deadline\",\"estimate_hours\",\"priority\"} ],\n",
    "        \"study_preferences\": {\"pomodoro\": True, \"session_length_min\":25}\n",
    "    }\n",
    "    \"\"\"\n",
    "    tasks = parse_tasks(student_profile[\"tasks\"])\n",
    "    prioritized = prioritize(tasks)\n",
    "    daily_plan = generate_daily_plan(prioritized, student_profile.get(\"daily_hours\", 3))\n",
    "    \n",
    "    # create subtasks\n",
    "    subtasks = {}\n",
    "    for t in prioritized:\n",
    "        subtasks[t[\"title\"]] = split_task_into_subtasks(t[\"title\"], t[\"estimate_hours\"])\n",
    "    \n",
    "    # build a prompt to ask LLM for resource links and micro-feedback\n",
    "    user_prompt = f\"\"\"\n",
    "Student name: {student_profile.get('name','Student')}\n",
    "Daily hours available: {student_profile.get('daily_hours',3)}\n",
    "Top 5 tasks (title, estimate_hours, deadline):\n",
    "{json.dumps(prioritized[:5], default=str, indent=2)}\n",
    "\n",
    "Produce:\n",
    "1) A short motivational micro-feedback (1-2 lines).\n",
    "2) For each of the top tasks, suggest 2 high-level learning resources or search queries (not raw URLs).\n",
    "3) A short pomodoro schedule template using student preferences: {student_profile.get('study_preferences',{})}\n",
    "Output the response as JSON with keys: 'micro_feedback','resources', 'pomodoro_template'.\n",
    "\"\"\"\n",
    "    llm_out = call_llm(SYSTEM_PROMPT, user_prompt)\n",
    "    # try to parse JSON from LLM safely; if fails, keep text\n",
    "    try:\n",
    "        parsed = json.loads(llm_out)\n",
    "    except:\n",
    "        parsed = {\"llm_text\": llm_out}\n",
    "    \n",
    "    return {\n",
    "        \"prioritized_tasks\": prioritized,\n",
    "        \"daily_plan\": daily_plan,\n",
    "        \"subtasks\": subtasks,\n",
    "        \"llm_recommendation\": parsed\n",
    "    }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell D: Orchestrator\n",
    "# def run_student_agent(student_profile):\n",
    "#     \"\"\"\n",
    "#     student_profile: {\n",
    "#         \"name\": str,\n",
    "#         \"daily_hours\": float,\n",
    "#         \"tasks\": [ {\"title\",\"deadline\",\"estimate_hours\",\"priority\"} ],\n",
    "#         \"study_preferences\": {\"pomodoro\": True, \"session_length_min\":25}\n",
    "#     }\n",
    "#     \"\"\"\n",
    "#     tasks = parse_tasks(student_profile[\"tasks\"])\n",
    "#     prioritized = prioritize(tasks)\n",
    "#     daily_plan = generate_daily_plan(prioritized, student_profile.get(\"daily_hours\", 3))\n",
    "    \n",
    "#     # create subtasks\n",
    "#     subtasks = {}\n",
    "#     for t in prioritized:\n",
    "#         subtasks[t[\"title\"]] = split_task_into_subtasks(t[\"title\"], t[\"estimate_hours\"])\n",
    "    \n",
    "#     # build a prompt to ask LLM for resource links and micro-feedback\n",
    "#     user_prompt = f\"\"\"\n",
    "# Student name: {student_profile.get('name','Student')}\n",
    "# Daily hours available: {student_profile.get('daily_hours',3)}\n",
    "# Top 5 tasks (title, estimate_hours, deadline):\n",
    "# {json.dumps(prioritized[:5], default=str, indent=2)}\n",
    "\n",
    "# Produce:\n",
    "# 1) A short motivational micro-feedback (1-2 lines).\n",
    "# 2) For each of the top tasks, suggest 2 high-level learning resources or search queries (not raw URLs).\n",
    "# 3) A short pomodoro schedule template using student preferences: {student_profile.get('study_preferences',{})}\n",
    "# Output the response as JSON with keys: 'micro_feedback','resources', 'pomodoro_template'.\n",
    "# \"\"\"\n",
    "    # llm_out = call_llm(SYSTEM_PROMPT, user_prompt)\n",
    "    # # try to parse JSON from LLM safely; if fails, keep text\n",
    "    # try:\n",
    "    #     parsed = json.loads(llm_out)\n",
    "    # except:\n",
    "    #     parsed = {\"llm_text\": llm_out}\n",
    "    \n",
    "    # return {\n",
    "    #     \"prioritized_tasks\": prioritized,\n",
    "    #     \"daily_plan\": daily_plan,\n",
    "    #     \"subtasks\": subtasks,\n",
    "    #     \"llm_recommendation\": parsed\n",
    "    # }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No matches for old API patterns found in project files.\n"
     ]
    }
   ],
   "source": [
    "# Run in a notebook cell in the project folder\n",
    "import glob, re, pathlib\n",
    "\n",
    "patterns = [\n",
    "    r\"chat\\.completions\\.create\",\n",
    "    r\"ChatCompletion\\.create\",\n",
    "    r\"Completion\\.create\",\n",
    "    r\"openai\\.ChatCompletion\",\n",
    "    r\"client\\.chat\\.completions\",\n",
    "    r\"openai\\.Completion\",\n",
    "    r\"chat_completions\"\n",
    "]\n",
    "\n",
    "files = glob.glob(\"/.\", recursive=True)\n",
    "matches = []\n",
    "for f in files:\n",
    "    if any(f.endswith(ext) for ext in (\".py\", \".ipynb\", \".txt\", \".md\")):\n",
    "        try:\n",
    "            text = pathlib.Path(f).read_text(encoding=\"utf-8\", errors=\"ignore\")\n",
    "        except Exception:\n",
    "            continue\n",
    "        for p in patterns:\n",
    "            if re.search(p, text):\n",
    "                matches.append((f, p))\n",
    "                break\n",
    "\n",
    "if not matches:\n",
    "    print(\"No matches for old API patterns found in project files.\")\n",
    "else:\n",
    "    print(\"Found old-style API uses (file, matched pattern):\")\n",
    "    for m in matches:\n",
    "        print(m[0],\"->\",m[1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>deadline</th>\n",
       "      <th>estimate_hours</th>\n",
       "      <th>priority</th>\n",
       "      <th>days_left</th>\n",
       "      <th>score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>WT quiz prep</td>\n",
       "      <td>2025-11-30</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>9</td>\n",
       "      <td>109.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>DAA assignment 1</td>\n",
       "      <td>2025-12-05</td>\n",
       "      <td>6</td>\n",
       "      <td>1</td>\n",
       "      <td>14</td>\n",
       "      <td>114.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>DBMS project report</td>\n",
       "      <td>2025-12-12</td>\n",
       "      <td>8</td>\n",
       "      <td>2</td>\n",
       "      <td>21</td>\n",
       "      <td>221.8</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 title    deadline  estimate_hours  priority  days_left  score\n",
       "0         WT quiz prep  2025-11-30               3         1          9  109.3\n",
       "1     DAA assignment 1  2025-12-05               6         1         14  114.6\n",
       "2  DBMS project report  2025-12-12               8         2         21  221.8"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Cell E: Demo and display\n",
    "demo_profile = {\n",
    "    \"name\":\"Sush\",\"daily_hours\":4,\n",
    "    \"tasks\":[\n",
    "        {\"title\":\"DAA assignment 1\",\"deadline\":\"2025-12-05\",\"estimate_hours\":6,\"priority\":1},\n",
    "        {\"title\":\"DBMS project report\",\"deadline\":\"2025-12-12\",\"estimate_hours\":8,\"priority\":2},\n",
    "        {\"title\":\"WT quiz prep\",\"deadline\":\"2025-11-30\",\"estimate_hours\":3,\"priority\":1}\n",
    "    ],\n",
    "    \"study_preferences\":{\"pomodoro\":True,\"session_length_min\":25,\"break_min\":5}\n",
    "}\n",
    "\n",
    "out = run_student_agent(demo_profile)\n",
    "display(pd.DataFrame(out[\"prioritized_tasks\"]))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>title</th>\n",
       "      <th>hours</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2025-11-21</td>\n",
       "      <td>WT quiz prep</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2025-11-21</td>\n",
       "      <td>DAA assignment 1</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2025-11-22</td>\n",
       "      <td>DAA assignment 1</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2025-11-23</td>\n",
       "      <td>DAA assignment 1</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2025-11-23</td>\n",
       "      <td>DBMS project report</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2025-11-24</td>\n",
       "      <td>DBMS project report</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2025-11-25</td>\n",
       "      <td>DBMS project report</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         date                title  hours\n",
       "0  2025-11-21         WT quiz prep    3.0\n",
       "1  2025-11-21     DAA assignment 1    1.0\n",
       "2  2025-11-22     DAA assignment 1    4.0\n",
       "3  2025-11-23     DAA assignment 1    1.0\n",
       "4  2025-11-23  DBMS project report    3.0\n",
       "5  2025-11-24  DBMS project report    4.0\n",
       "6  2025-11-25  DBMS project report    1.0"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Cell F: Present daily plan as dataframe\n",
    "plan_rows = []\n",
    "for date, items in out[\"daily_plan\"].items():\n",
    "    for it in items:\n",
    "        plan_rows.append({\"date\": date, \"title\": it[\"title\"], \"hours\": it[\"hours\"]})\n",
    "df_plan = pd.DataFrame(plan_rows)\n",
    "df_plan.sort_values([\"date\"], inplace=True)\n",
    "df_plan.reset_index(drop=True, inplace=True)\n",
    "df_plan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Subtasks preview:\n",
      "- WT quiz prep -> []\n",
      "- DAA assignment 1 -> []\n",
      "- DBMS project report -> []\n",
      "\n",
      "LLM Recommendations:\n",
      "{\n",
      "  \"summary\": \"Start 'WT quiz prep'\"\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "# Cell G: Subtasks and LLM output\n",
    "print(\"Subtasks preview:\")\n",
    "for k,v in out[\"subtasks\"].items():\n",
    "    print(\"-\", k, \"->\", v[:3])\n",
    "print(\"\\nLLM Recommendations:\")\n",
    "print(json.dumps(out[\"llm_recommendation\"], indent=2, default=str))"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [],
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}